openl2m/openl2m/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
"""
openl2m URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.conf import settings
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordChangeView,
)
from django.urls import include, path

# from django.conf.urls import include
from django.http import HttpResponseRedirect

from users.views import MyLoginView, LogoutView
from openl2m.api.views import APIRootView, APIAdminRootView, APIStatsView, APIEnvironmentView

# Custom admin site:
from .admin import admin_site

app_name = "openl2m"
urlpatterns = [
    # / view redirects to the "switches" app
    path("", lambda r: HttpResponseRedirect("switches/"), name="home"),
    # our own customized form for logout
    # note that we capture login/logout signals in "users/models.py", so we can add log entries
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/login/", MyLoginView.as_view(), name="login"),
    # override some of the password templates, so we can disabled that for ldap
    path(
        "accounts/password_change/",
        PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done",
    ),
    # and the rest are not used:
    # url(r'^accounts/$', include('django.contrib.auth.urls')),
    # application paths
    path("switches/", include("switches.urls")),
    # user profiles, etc.
    path("users/", include("users.urls")),
    # Admin - customized, see admin.py
    path("admin/", admin_site.urls),
    #
    # API paths
    path("api/", APIRootView.as_view(), name="api-root"),
    path("api/switches/", include("switches.api.urls"), name="switches-api"),
    path("api/stats/", APIStatsView.as_view(), name='api-stats'),
    path("api/environment/", APIEnvironmentView.as_view(), name='api-environment'),
    path("api/users/", include("users.api.urls"), name="users-api"),
    # admin paths:
    path("api/admin/", APIAdminRootView.as_view(), name="api-admin-root"),
    path("api/admin/users/", include("users.api.admin.urls"), name="api-admin-users"),
    path("api/admin/switches/", include("switches.api.admin.urls"), name="api-admin-switches"),
    # to be implemented:
    # path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    # path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),
]

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    # import debug_toolbar
    urlpatterns += [
        # debug toolbar:
        path("__debug__/", include("debug_toolbar.urls")),
    ]

openl2m/switches/api/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path

from switches.api.views import (
    APISwitchMenuView,
    APISwitchSearch,
    APISwitchBasicView,
    APISwitchDetailsView,
    APISwitchSaveConfig,
    APISwitchVlanAdd,
    APISwitchVlanEdit,
    APISwitchVlanDelete,
    APIInterfaceSetVlan,
    APIInterfaceSetState,
    APIInterfaceSetPoE,
    APIInterfaceSetDescription,
)

app_name = 'switches-api'

# api switch views
urlpatterns = [
    path(
        "",
        APISwitchMenuView.as_view(),
        name="api_switch_menu_view",
    ),
    path(
        "search/<str:name>/",
        APISwitchSearch.as_view(),
        name="api_switch_search",
    ),
    path(
        "<int:group_id>/<int:switch_id>/",
        APISwitchBasicView.as_view(),
        name="api_switch_view",
    ),
    path(
        "<int:group_id>/<int:switch_id>/details/",
        APISwitchDetailsView.as_view(),
        name="api_switch_details_view",
    ),
    path(
        "<int:group_id>/<int:switch_id>/save/",
        APISwitchSaveConfig.as_view(),
        name="api_switch_save_config",
    ),
    path(
        "<int:group_id>/<int:switch_id>/vlan/add/",
        APISwitchVlanAdd.as_view(),
        name="api_switch_vlan_add",
    ),
    path(
        "<int:group_id>/<int:switch_id>/vlan/edit/",
        APISwitchVlanEdit.as_view(),
        name="api_switch_vlan_edit",
    ),
    path(
        "<int:group_id>/<int:switch_id>/vlan/delete/",
        APISwitchVlanDelete.as_view(),
        name="api_switch_vlan_delete",
    ),
    path(
        "<int:group_id>/<int:switch_id>/interface/<ifname:interface_id>/vlan/",
        APIInterfaceSetVlan.as_view(),
        name="api_interface_set_vlan",
    ),
    path(
        "<int:group_id>/<int:switch_id>/interface/<ifname:interface_id>/state/",
        APIInterfaceSetState.as_view(),
        name="api_interface_set_state",
    ),
    path(
        "<int:group_id>/<int:switch_id>/interface/<ifname:interface_id>/poe_state/",
        APIInterfaceSetPoE.as_view(),
        name="api_interface_set_poe_state",
    ),
    path(
        "<int:group_id>/<int:switch_id>/interface/<ifname:interface_id>/description/",
        APIInterfaceSetDescription.as_view(),
        name="api_interface_set_description",
    ),
]

openl2m/switches/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path, register_converter

from django.conf import settings

# from django.conf.urls import url

from switches import views


class InterfaceNameConvertor:
    # convertor class to make sure interface names follow url-safe formats

    # regex entry is required, and used for reverse to validate allowed characters in "ifname"
    regex = r"[a-zA-Z0-9\/_\-:]*"

    def to_python(self, value):
        # replace _ with /
        return value.replace("_", "/")

    def to_url(self, value):
        # replace / with _
        return value.replace("/", "_")


register_converter(
    InterfaceNameConvertor,
    "ifname",
)

app_name = "switches"
urlpatterns = [
    path(
        '',
        views.Switches.as_view(),
        name='groups',
    ),
    path(
        'search',
        views.SwitchSearch.as_view(),
        name='switch_search',
    ),
    path(
        'activity',
        views.SwitchAdminActivity.as_view(),
        name='admin_activity',
    ),
    path(
        'stats',
        views.ShowStats.as_view(),
        name='show_stats',
    ),
    path(
        'top',
        views.ShowTop.as_view(),
        name='show_top',
    ),
    path(
        '<int:group_id>/<int:switch_id>/',
        views.SwitchBasics.as_view(),
        name='switch_basics',
    ),
    path(
        '<int:group_id>/<int:switch_id>/activity/',
        views.SwitchActivity.as_view(),
        name='switch_activity',
    ),
    path(
        '<int:group_id>/<int:switch_id>/bulkedit/',
        views.SwitchBulkEdit.as_view(),
        name='switch_bulkedit',
    ),
    path(
        '<int:group_id>/<int:switch_id>/vlan_manage/',
        views.SwitchVlanManage.as_view(),
        name='switch_vlan_manage',
    ),
    path(
        '<int:group_id>/<int:switch_id>/command/',
        views.SwitchCmdOutput.as_view(),
        name='switch_cmd_output',
    ),
    path(
        '<int:group_id>/<int:switch_id>/command_template/',
        views.SwitchCmdTemplateOutput.as_view(),
        name='switch_cmd_template_output',
    ),
    path(
        '<int:group_id>/<int:switch_id>/details/',
        views.SwitchDetails.as_view(),
        name='switch_arp_lldp',
    ),
    path(
        '<int:group_id>/<int:switch_id>/reload/<str:view>/',
        views.SwitchReload.as_view(),
        name='switch_reload',
    ),
    path(
        '<int:group_id>/<int:switch_id>/save/',
        views.SwitchSaveConfig.as_view(),
        name='switch_save_config',
    ),
    path(
        '<int:group_id>/<int:switch_id>/download_ethernet/',
        views.SwitchDownloadEthernetAndNeighbors.as_view(),
        name='switch_download_ethernet_neighbors',
    ),
    path(
        '<int:group_id>/<int:switch_id>/download_interfaces/',
        views.SwitchDownloadInterfaces.as_view(),
        name='switch_download_interfaces',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/admin/<int:new_state>/',
        views.InterfaceAdminChange.as_view(),
        name='admin_change',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/newdescription/',
        views.InterfaceDescriptionChange.as_view(),
        name='description_change',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/newpvid/',
        views.InterfacePvidChange.as_view(),
        name='pvid_change',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/poe/<int:new_state>/',
        views.InterfacePoeChange.as_view(),
        name='poe_change',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/poetoggle/',
        views.InterfacePoeDownUp.as_view(),
        name='poe_down_up',
    ),
    path(
        '<int:group_id>/<int:switch_id>/<ifname:interface_name>/command/',
        views.InterfaceCmdOutput.as_view(),
        name='interface_cmd_output',
    ),
]

if settings.DEBUG:
    urlpatterns += [
        # HTML test page:
        path(
            'testpage',
            views.TestPage.as_view(),
            name='test_page',
        )
    ]

openl2m/users/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('theme/<str:name>/', views.ThemeView.as_view(), name='theme'),
    path('menu/<int:menu>/', views.MenuView.as_view(), name='menu'),
    path('info/<int:user_id>/', views.InfoView.as_view(), name='info'),
    path('tokens/', views.TokenListView.as_view(), name='token_list'),
    path('tokens/add/', views.TokenAdd.as_view(), name='token_add'),
    path('tokens/edit/<int:token_id>/', views.TokenEdit.as_view(), name='token_edit'),
    path('tokens/delete/<int:token_id>/', views.TokenDelete.as_view(), name='token_delete'),
    #    path('tokens/<int:pk>/', include(get_model_urls('users', 'token'))),
]

openl2m/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm">
  <div class="container-fluid">
<!-- <h1 class="navbar-brand pb-0"> -->
{% if request.user.is_authenticated and not is_top_menu %}
      <form class="navbar-brand pb-0 mb-0"
        action="{% url 'switches:groups' %}"
        method="post"
      {% if connection.save_needed %}
        onclick="return confirm_change('There are UNSAVED changes, are you sure?')"
      {% endif %}
      >
        {% csrf_token %}
        <input type="image" src="{% static 'img/openl2m-logo.png' %}"
            data-bs-toggle="tooltip"
            data-bs-title="Go back to Devices Menu"
            alt="OpenL2M logo"
        >
      </form>
{% else %}
    <img src="{% static 'img/openl2m-logo.png' %}" alt="OpenL2M logo">
{% endif %}
<!-- </h1> -->

{% if request.user.is_authenticated %}

  {% if settings.SWITCH_SEARCH_FORM %}
    <div class="navbar-collapse ms-4">
      <form class="d-flex"
            name="switch_search_form"
            action="{% url 'switches:switch_search' %}"
            method="post"
      >
        <div class="input-group border border-light-subtle rounded">
          {% csrf_token %}
          <input type="text" name="switchname" id="switchname"
                class="form-control border border-light-subtle rounded"
                placeholder="Device name or reg-ex..."
                data-bs-toggle="tooltip"
                title="Type the name or regular expression of the device(s) you are looking for here!"
                onkeyup="validateSearch()">
          <button type="submit" name="search_submit" id="search_submit" disabled
                value="Search"
                class="btn color-openl2m"
                data-bs-toggle="tooltip"
                title="Click here to search for a device!"
          ><i class="fa-solid fa-search"></i></button>
        </div>
      </form>
      <script>
        function validateSearch() {
          const submitButton = document.getElementById('search_submit');
          if (document.getElementById('switchname').value.trim() !== "") {
            submitButton.disabled = false   // Input changes, enable the search button
          } else {
            submitButton.disabled = true    // No changes from original, disable the search button
          }
        }
      </script>
    </div>
  {% endif %}

    <div class="position-absolute end-0" id="navbarContent">
      <ul class="navbar-nav me-auto">
      {% if settings.MENU_INFO_URLS %}
        {% for headername,menus in settings.MENU_INFO_URLS.items %}
        <li class="nav-item dropdown">
<!--          <ul class="nav navbar-nav
          {% if settings.MENU_ON_RIGHT %}
            navbar-right
          {% endif %}
          "> -->
          <a class="nav-link dropdown-toggle" href="#" id="navbarMenu{{ forloop.counter }}" role="button" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">{{ headername }}</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarMenu{{ forloop.counter }}">
          {% for menu in menus %}
            <li><a class="dropdown-item" href="{{ menu.url }}"
            {% if menu.target %}
                target="{{ menu.target }}"
            {% endif %}
            {% if menu.hint %}
                data-bs-toggle="tooltip" data-bs-title="{{ menu.hint }}"
            {% endif %}
            >
            {% if menu.fa_icon %}
              <i class="fa-solid {{ menu.fa_icon }} aria-hidden="true"></i>
            {% elif menu.icon %}
              <img src="{{ menu.icon }}"
              {% if menu.alt %}
                alt="{{ menu.alt }}"
              {% endif %}
              >
            {% endif %}
            {{ menu.name }}</a></li>
          {% endfor %}
          </ul>
      {% endfor %}
        </li>
      {% endif %}{# end MENU_INFO_URLS #}

        {# user menu #}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ request.user|truncatechars:"30" }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarUserDropdown">
            <li><a class="dropdown-item" href="{% url 'switches:groups' %}"><i class="fa-solid fa-ethernet"></i> Home</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% static 'docs/html/what_is_new.html' %}" target="_blank"><i class="fa-solid fa-star" aria-hidden="true"></i> What&apos;s New!</a></li>
            <li><a class="dropdown-item" href="{% static 'docs/html/using/index.html' %}" target="_blank"><i class="fa-solid fa-book" aria-hidden="true"></i> Documentation</a></li>
            {% if request.user.is_superuser %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa-solid fa-pen"></i> Administration</a></li>
              {% if switch %}
              <li><a class="dropdown-item" href="{% url 'admin:switches_switch_change' switch.id %}">&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-ethernet"></i> This Device</a></li>
              {% endif %}
              {% if group %}
              <li><a class="dropdown-item" href="{% url 'admin:switches_switchgroup_change' group.id %}">&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-user-friends"></i> This Group</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'switches:admin_activity' %}"><i class="fa-solid fa-list-ul" aria-hidden="true"></i> Activity Logs</a></li>
            {% elif request.user.is_staff %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'switches:admin_activity' %}"><i class="fa-solid fa-list-ul" aria-hidden="true"></i> Activity Logs</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'switches:show_stats' %}"><i class="fa-solid fa-chart-pie" aria-hidden="true"></i> Usage Statistics</a></li>
            {% if settings.TOP_ACTIVITY %}
            <li><a class="dropdown-item" href="{% url 'switches:show_top' %}"><i class="fa-solid fa-mountain" aria-hidden="true"></i> Top Usage</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="https://github.com/openl2m/openl2m/" target="_blank"><i class="fa-solid fa-code" aria-hidden="true"></i> Code</a></li>
            <li><hr class="dropdown-divider"></li>
            {% if not request.user.ldap_user %}
            <li><a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa-solid fa-key"></i> Change Password</a></li>
            {% endif %}
            {% if request.path == '/switches/' %}
              {# Choose theme menu, only on top level menu page #}
              {% if request.user.profile.theme == 'light' %}
                <li><a class="dropdown-item" href="{% url 'users:theme' 'dark' %}"><i class="fa-solid fa-clone"></i> Set Dark Mode</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'users:theme' 'light' %}"><i class="far fa-clone"></i> Set Light Mode</a></li>
              {% endif %}
              {# Show or Hide device menu #}
              {% if request.user.profile.menu %}
                <li><a class="dropdown-item" href="{% url 'users:menu' '0' %}"><i class="far fa-bars"></i> Hide Menu</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'users:menu' '1' %}"><i class="fa-solid fa-bars"></i> Show Menu</a></li>
              {% endif %}
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'users:token_list' %}"><i class="fa-solid fa-user-secret"></i> API Tokens</a></li>
            <li><a class="dropdown-item" href="{% url 'users:profile' %}"><i class="fa-solid fa-user-circle"></i> Profile</a></li>
            <li> <hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" ><i class="fa-solid fa-info" aria-hidden="true"></i> OpenL2M v{{ settings.VERSION }}</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fa-solid fa-sign-out-alt"></i> Log out</a></li>
          </ul>
        </li>
      </ul>{# navbar-nav #}
    </div>{# navbarContent #}
{% endif %}{# authenticated #}
  </div>{# container-fluid #}
</nav>

openl2m/templates/admin_stats.html
{% extends '_base.html' %}

{% block title %}Stats{% endblock %}

{% block content %}

{# see https://codepen.io/sinairv/pen/XjZyWP #}
<div class="container">
  <div class="row">

    <div class="col">
      <div class="card border-default">
        <div class="card-header bg-default">
            <strong>OpenL2M Statistics</strong>
        </div>
        <ul class="list-group list-group-flush">
        {% for attribute,data in db_items.items %}
          <li class="list-group-item">{{ data.label }}: {{ data.value }}</li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card border-default">
        <div class="card-header bg-default">
          <strong>Usage</strong>
        </div>
        <ul class="list-group list-group-flush">
        {% for attribute,data in usage.items %}
          <li class="list-group-item">{{ data.label }}: {{ data.value }}</li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card border-default">
        <div class="card-header bg-default">
          <strong>Environment</strong>
        </div>
        <ul class="list-group list-group-flush">
        {% for attribute,data in environment.items %}
          <li class="list-group-item">{{ data.label }}: {{ data.value }}</li>
        {% endfor %}
          <li class="list-group-item">OS Time: {% now 'D, d M Y H:i:s T' %}</li>
        </ul>
      </div>
    </div>

    <div class="col">
      <div class="card border-default">
        <div class="card-header bg-default">
          <strong>Active Users</strong>
        </div>
        <ul class="list-group list-group-flush">
        {% for u in user_list %}
          <li class="list-group-item">
          {% if request.user.is_superuser or request.user.is_staff %}
              <a href="{% url 'users:info' u.id %}"
               data-bs-toggle="tooltip"
               title="Click here to see info on this user...">{{ u.username }}</a>
          {% else %}
              {{ u.username }}
          {% endif %}
          {% if u.hostname %}
                (<abbr data-bs-toggle="tooltip" title="{{ u.hostname }}">{{ u.remote_ip }}</abbr>)
          {% else %}
               ({{ u.remote_ip }})
          {% endif %}
          {% if request.user.is_superuser %}
              <a href="{% url 'switches:admin_activity' %}?user={{ u.id }}"
               data-bs-toggle="tooltip" title="Click here to see user activity logs...">Activity logs</a>
          {% endif %}
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>{# row #}
</div>{# container #}

{% endblock %}

openl2m/templates/home.html
{% extends '_base.html' %}

<!--  Home page! This shows the list of devices a user has access to  -->

{% block content %}

{% load helpers %}

{% if group_count == 0 %}
    <div class="card border-warning">
        <div class="card-header bg-warning">
        <i class="fa-solid fa-exclamation-triangle"></i>
            &nbsp;<strong>No groups assigned!</strong>
        </div>
        <div class="card-body row justify-content-md-center">
            You are not a member of any switch groups! Please contact the OpenL2M administrator.
        </div>
    </div>
{% elif user.profile.menu %}
    <div class="container-fluid">
        <div class="card border-default">
            <div class="card-header bg-default">
                <strong>My Device
    {% if group_count == 1 %}
                Group:
    {% else %}
                Groups:
    {% endif %}
                </strong>
            </div>{# card header #}
            {# start groups wrapper #}
            <div class="card-body">

    {# max_columns and col_width are vars passed into template! #}
    <!-- max_columns = {{ max_columns }}, col_width = {{ col_width }} -->
    {% for group_id, group in groups.items %}
        <!-- counter = {{ forloop.counter0 }} -->
        {% if forloop.counter0|divisibleby:max_columns %}
                <!--  new row  -->
                <div class="row">
        {% endif %}
                    <!--  add new column  -->
                    <div class="col-{{ col_width }}">
                        <!-- START Group {{ group_id }} '{{ group.name }}' -->
                        {# header for collapsible items, i.e. the switchgroup name #}
                        <div class="d-grid">

<!--
                   # parse open/closed options:
                    if open:
                        expanded = "true"
                        show = "show"
                    else:
                        expanded = "false"
                        show = ""
-->

                        {# wrap description around the menu button, set full size...#}
                            {# add the button #}
                            <button class="btn btn-outline-secondary mb-2"
                                type="button"
                                data-bs-toggle="collapse" data-bs-target="#group{{ group_id }}"
                            {% if group_count == 1 %}
                                aria_expanded="true"
                            {% else %}
                                aria-expanded="false"
                            {% endif %}
                                aria-controls="group{{ group_id }}">
                            {% if group.description %}
                                <span class="d-grid" data-bs-toggle="tooltip" data-bs-title="{{ group.description }}">
                            {% endif %}
                            {# use display name if set, else just group name #}
                            {% if group.display_name %}
                                {{ group.display_name }}
                            {% else %}
                                {{ group.name }}
                            {% endif %}
                            {% if group.read_only %}:
                                (r/o)
                            {% endif %}
                            {% if group.description %}
                            {# end description wrapper span #}
                                </span>
                            {% endif %}
                            {# end button #}
                            </button>
                        {# end d-grip #}
                        </div>

                        {# the list of devices in this menu, ie collapsible items #}
                        <div class="collapse overflow-scroll{% if group_count == 1 %} show{% endif %}"
                             id="group{{ group_id }}"
                             style="max-height: 200px;">
                            <div class="list-group">
                            {% for switch_id, switch in group.members.items %}
                                <form
                                    method="post"
                                    id="{{ group_id }}_{{ switch_id}}"
                                    style="cursor: pointer;"
                                    class="list-group-item list-group-item-action"
                                    {% if switch.default_view == SWITCH_VIEW_BASIC %}
                                        action="{% url 'switches:switch_basics' group_id switch_id %}"
                                    {% else %}
                                        action="{% url 'switches:switch_arp_lldp' group_id switch_id %}"
                                    {% endif %}>
                                    {% csrf_token %}
                                    <span onclick="submit_{{ group_id }}_{{ switch_id}}()">{{ switch.name }}</span>
                                    <script>
                                        function submit_{{ group_id }}_{{ switch_id}}() {
                                        let form = document.getElementById("{{ group_id }}_{{ switch_id}}");
                                        form.submit();
                                        }
                                    </script>
                                </form>
                            {% endfor %}
                            </div>
                        </div>
                        <!-- END Group {{ group.id }} -->



                    <!--  and end this group column  -->
                    </div>

        {% with col_count=forloop.counter|divisibleby:max_columns %}
                    <!-- col_count = {{ col_count }} -->
            {% if col_count  %}
                </div> <!--  end row-->
            {% endif %}
        {% endwith %}
    {% endfor %}

    <!--  end the last row, and container, if needed  -->
    {% if max_columns > 1 %}
                </div><!--  column  -->
    {% endif %}

            </div> <!--  card-body  -->
        </div> <!--  card  -->
    </div> <!--  container  -->

{% endif %}
{% endblock %}