openl2m/openl2m/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
"""
openl2m URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.conf import settings
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordChangeView,
)
from django.urls import include, path

# from django.conf.urls import include
from django.http import HttpResponseRedirect

from users.views import MyLoginView, LogoutView
from openl2m.api.views import APIRootView, APIAdminRootView, APIStatsView, APIEnvironmentView

# Custom admin site:
from .admin import admin_site

app_name = "openl2m"
urlpatterns = [
    # / view redirects to the "switches" app
    path("", lambda r: HttpResponseRedirect("switches/"), name="home"),
    # our own customized form for logout
    # note that we capture login/logout signals in "users/models.py", so we can add log entries
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/login/", MyLoginView.as_view(), name="login"),
    # override some of the password templates, so we can disabled that for ldap
    path(
        "accounts/password_change/",
        PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done",
    ),
    # and the rest are not used:
    # url(r'^accounts/$', include('django.contrib.auth.urls')),
    # application paths
    path("switches/", include("switches.urls")),
    # user profiles, etc.
    path("users/", include("users.urls")),
    # Admin - customized, see admin.py
    path("admin/", admin_site.urls),
    #
    # API paths
    path("api/", APIRootView.as_view(), name="api-root"),
    path("api/switches/", include("switches.api.urls"), name="switches-api"),
    path("api/stats/", APIStatsView.as_view(), name='api-stats'),
    path("api/environment/", APIEnvironmentView.as_view(), name='api-environment'),
    path("api/users/", include("users.api.urls"), name="users-api"),
    # admin paths:
    path("api/admin/", APIAdminRootView.as_view(), name="api-admin-root"),
    path("api/admin/users/", include("users.api.admin.urls"), name="api-admin-users"),
    path("api/admin/switches/", include("switches.api.admin.urls"), name="api-admin-switches"),
    # to be implemented:
    # path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    # path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),
]

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    # import debug_toolbar
    urlpatterns += [
        # debug toolbar:
        path("__debug__/", include("debug_toolbar.urls")),
    ]

openl2m/users/api/admin/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path

from users.api.admin.views import APIAdminUsers, APIAdminUserDetail

app_name = 'api-admin-users'

urlpatterns = [
    # api token path @post only
    path("", APIAdminUsers.as_view(), name="api-admin-users"),
    path("<int:pk>/", APIAdminUserDetail.as_view(), name="api-admin-user-detail"),
]

openl2m/users/api/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path

from users.api.views import APIObtainAuthToken

app_name = 'users-api'

# users api views
urlpatterns = [
    # api token path @post only
    path(
        "token/",
        APIObtainAuthToken.as_view(),
        name="api-token",
    ),
]

openl2m/users/urls.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('theme/<str:name>/', views.ThemeView.as_view(), name='theme'),
    path('menu/<int:menu>/', views.MenuView.as_view(), name='menu'),
    path('info/<int:user_id>/', views.InfoView.as_view(), name='info'),
    path('tokens/', views.TokenListView.as_view(), name='token_list'),
    path('tokens/add/', views.TokenAdd.as_view(), name='token_add'),
    path('tokens/edit/<int:token_id>/', views.TokenEdit.as_view(), name='token_edit'),
    path('tokens/delete/<int:token_id>/', views.TokenDelete.as_view(), name='token_delete'),
    #    path('tokens/<int:pk>/', include(get_model_urls('users', 'token'))),
]

openl2m/users/api/admin/views.py
#
# This file is part of Open Layer 2 Management (OpenL2M).
#
# OpenL2M is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.  You should have received a copy of the GNU General Public
# License along with OpenL2M. If not, see <http://www.gnu.org/licenses/>.
#

#
# Here we implement all user admin API views as classes
#
from django.contrib.auth.models import User
from rest_framework import permissions, viewsets
from rest_framework import status as http_status
from rest_framework.response import Response
from rest_framework.views import APIView

from switches.utils import dprint, get_remote_ip
from switches.constants import (
    LOG_TYPE_CHANGE,
    LOG_TYPE_ERROR,
    LOG_TYPE_VIEW,
    LOG_REST_API_ADMIN_USER_GET_ALL,
    LOG_REST_API_ADMIN_USER_CREATE,
    LOG_REST_API_ADMIN_USER_GET,
    LOG_REST_API_ADMIN_USER_MODIFY,
)
from switches.models import Log

from users.api.admin.serializers import UserSerializer, ProfileSerializer
from users.api.admin.utils import add_user_to_switchgroups, update_user_profile

from openl2m.api.authentication import IsSuperUser


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class APIAdminUsers(APIView):
    '''
    API Class to return all users (GET), or create a new user (POST)
    '''

    permission_classes = [IsSuperUser]

    # get all users
    def get(self, request):
        dprint(f"APIAdminUsers(GET)- get all by '{request.user.username}'")
        # return all users.
        users = User.objects.all()
        serializer = UserSerializer(users, many=True, context={'request': request})
        log = Log(
            type=LOG_TYPE_VIEW,
            action=LOG_REST_API_ADMIN_USER_GET_ALL,
            user=request.user,
            ip_address=get_remote_ip(request),
            description="API Admin get all users",
        )
        log.save()
        return Response(data=serializer.data, status=http_status.HTTP_200_OK)

    # create a new user
    def post(self, request):
        dprint("APIAdminUsers(POST) - create new user")
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            return_data = serializer.data
            add_user_to_switchgroups(request, user)
            profile = update_user_profile(request, user)
            if profile:
                # add profile data to return
                profile_serializer = ProfileSerializer(profile)
                return_data['profile'] = profile_serializer.data
            log = Log(
                type=LOG_TYPE_CHANGE,
                action=LOG_REST_API_ADMIN_USER_CREATE,
                user=request.user,
                ip_address=get_remote_ip(request),
                description=f"API Admin create user, parameters: {request.data}",
            )
            log.save()
            return Response(data=return_data, status=http_status.HTTP_201_CREATED)
        # invalid data:
        log = Log(
            type=LOG_TYPE_ERROR,
            action=LOG_REST_API_ADMIN_USER_CREATE,
            user=request.user,
            ip_address=get_remote_ip(request),
            description=f"API Admin create user error: '{serializer.errors}', parameters: {request.data}",
        )
        log.save()
        return Response(serializer.errors, status=http_status.HTTP_400_BAD_REQUEST)


class APIAdminUserDetail(APIView):
    '''
    API class to read (GET) or update (PATCH) the details of a user.
    '''

    permission_classes = [IsSuperUser]

    def get(self, request, pk):
        '''GET return the user object for a primary key 'pk' '''
        dprint(f"APIAdminUserDetail.get(): pk={pk}, user={request.user.username}, profile={request.user.profile}")
        try:
            user = User.objects.get(pk=pk)
        except Exception:
            # log the error
            log = Log(
                type=LOG_TYPE_ERROR,
                action=LOG_REST_API_ADMIN_USER_GET,
                user=request.user,
                ip_address=get_remote_ip(request),
                description=f"API Admin get user error: unknown id={pk}",
            )
            log.save()
            # return error
            return Response(
                data={
                    "reason": "Invalid user id!",
                },
                status=http_status.HTTP_400_BAD_REQUEST,
            )
        serializer = UserSerializer(user, context={'request': request})
        # also get the profile
        profile_serializer = ProfileSerializer(user.profile, context={'request': request})
        # collect user and profile data
        data = serializer.data
        data['profile'] = profile_serializer.data
        # log the request
        log = Log(
            type=LOG_TYPE_VIEW,
            action=LOG_REST_API_ADMIN_USER_GET,
            user=request.user,
            ip_address=get_remote_ip(request),
            description=f"API Admin get user for pk={pk}, user={user.name}",
        )
        log.save()
        # and return it:
        return Response(
            data=data,
            status=http_status.HTTP_200_OK,
        )

    def patch(self, request, pk):
        dprint("APIAdminUserDetail.patch() passing to post")
        return self.post(request, pk)

    def post(self, request, pk):
        '''Handle POST to update attributes of the User object for private key 'pk' '''
        dprint(f"APIAdminUserDetail.post(): pk={pk}, user={request.user.username}")
        try:
            user = User.objects.get(pk=pk)
        except Exception:
            # log the error
            log = Log(
                type=LOG_TYPE_ERROR,
                action=LOG_REST_API_ADMIN_USER_MODIFY,
                user=request.user,
                ip_address=get_remote_ip(request),
                description=f"API Admin modify user error: unknown id={pk}",
            )
            log.save()
            # send the error
            return Response(
                data={
                    "reason": "Invalid user id!",
                },
                status=http_status.HTTP_400_BAD_REQUEST,
            )
        serializer = UserSerializer(user, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return_data = serializer.data
            add_user_to_switchgroups(request, user)
            profile = update_user_profile(request, user)
            if profile:
                # add profile data to return
                profile_serializer = ProfileSerializer(profile)
                return_data['profile'] = profile_serializer.data
                # log the change
                log = Log(
                    type=LOG_TYPE_CHANGE,
                    action=LOG_REST_API_ADMIN_USER_MODIFY,
                    user=request.user,
                    ip_address=get_remote_ip(request),
                    description=f"API Admin modify user for id={pk}, user={user.name}, parameters={request.data}",
                )
                log.save()

            return Response(
                data=return_data,
                # data={'result': f"User id {pk} has been updated!"},
                status=http_status.HTTP_200_OK,
            )
        # log the error:
        log = Log(
            type=LOG_TYPE_ERROR,
            action=LOG_REST_API_ADMIN_USER_MODIFY,
            user=request.user,
            ip_address=get_remote_ip(request),
            description=f"API Admin modify user error for id={pk}, user={user.name}: {serializer.errors}",
        )
        log.save()

        return Response(serializer.errors, status=http_status.HTTP_400_BAD_REQUEST)

openl2m/templates/users/profile.html
{% extends '_base.html' %}
{% load helpers %}

{% block title %}User Profile{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card border-default">
        <div class="card-header bg-default">
        {% if request.user.id == user.id %}
          <strong>Your User Profile</strong>
        {% else %}
          <strong>User Profile for '{{ user.username }}'</strong>
        {% endif %}
        </div>
        <div class="card-body">
          <table class="table table-hover table-headings w-auto">
            <tbody>
            <tr><td>Login Name</td><td>{{ user.username }}</td></tr>
            <tr><td>Full Name</td>
              {% if user.first_name and user.last_name %}
              <td>{{ user.first_name }} {{ user.last_name }}</td>
              {% else %}
              <td>(not set)</td>
              {% endif %}
            </tr>
            <tr><td>Email</td><td>{{ user.email }}</td></tr>
            <tr><td>Last Login</td><td>{{ user.last_login }}</td></tr>
            {% if user.ldap_user %}
            <tr><td>LDAP DN</td><td>{{ user.ldap_user.dn }}</td></tr>
            {% elif user.profile.last_ldap_dn %}
            <tr><td>Last LDAP DN</td><td>{{ user.profile.last_ldap_dn }}</td></tr>
            {% else %}
            <tr><td>Local Login</td><td>Yes</td></tr>
            {% endif %}
            <tr><td>Registered</td><td>{{ user.date_joined }}</td></tr>
            <tr><td><strong>Settings:</strong></td><td></td></tr>
            <tr><td>Switch Groups</td><td>{{ user.switchgroups.all|join:', ' }}</td></tr>
            <tr><td>Staff Access</td><td>{{ user.is_staff|yesno|capfirst }}</td></tr>
            <tr><td>Admin Access</td><td>{{ user.is_superuser|yesno|capfirst }}</td></tr>
            <tr><td>Read-Only Access</td><td>{{ user.profile.read_only|yesno|capfirst }}</td></tr>
            <tr><td>Bulk-Edit Access</td><td>{{ user.profile.bulk_edit|yesno|capfirst }}</td></tr>
            <tr><td>PoE Toggle</td><td>{{ user.profile.allow_poe_toggle|yesno|capfirst }}</td></tr>
            <tr><td>Edit Description</td><td>{{ user.profile.edit_if_descr|yesno|capfirst }}</td></tr>
            <tr><td>Ask Are You Sure?</td><td>{{ user.profile.are_you_sure|yesno|capfirst }}</td></tr>
            <tr><td>Show Menu</td><td>{{ user.profile.menu|yesno|capfirst }}</td></tr>
            <tr><td>Theme</td><td>{{ user.profile.theme }}</td></tr>
            {% if tokens %}
            <tr><td><strong>API Tokens:</strong></td><td></td></tr>
              {% for token in tokens %}
            <tr><td>#{{ forloop.counter }}</td><td>{{ token.partial }}{% if token.description %} - {{ token.description }} {% endif %}</td></tr>
              {% endfor %}
            {% endif %}
          </tbody>
          </table>
        </div>{# card-body #}
      </div>{# card #}
    </div>{# col #}
  </div>{# row #}
</div>{# container #}
{% endblock %}

openl2m/templates/users/token_edit.html
{% extends '_base.html' %}
{% load helpers %}

{% block title %}API Token{% endblock %}

{% block content %}
<div class="row">
  <div class="col">
    <div class="card border-default">
      <div class="card-header bg-default">
        {% if action == "edit" %}
            <strong>Edit your API Token</strong>
        {% else %}
            <strong>Add an API Token</strong>
        {% endif %}
      </div>
      <div class="card-body">
        {% if action == "edit" %}
        <form name="token_edit"
          action="{% url 'users:token_edit' token.id %}"
          method="post"
          >
        {% else%}
          <form name="token_add"
          action="{% url 'users:token_add' %}"
          method="post"
          >
        {% endif %}
        {% csrf_token %}
        <table class="table table-hover table-headings">
          <tbody>
          <tr>
            <th>Token</th>
            {% if action == "add" %}
                <th><input type="text" size=80 name="key" value="{{ token.key }}"
                    data-bs-toggle="tooltip" title="This is your new token!" readonly /></th>
            {% else %}
              {% if settings.ALLOW_TOKEN_RETRIEVAL %}
                <th>{{token.key }}</th>
              {% else %}
                <th>{{token.partial }}</th>
              {% endif %}
            {% endif %}
          </tr>
          <tr>
            <td>Description</td>
            <td><input type="text" size=80 name="description" value="{{ token.description }}"
            data-bs-toggle="tooltip" title="Type a token description here!" /></td>
          </tr>
{% if not user.profile.read_only %}
          <tr>
            <td>Writable</td>
            <td><input type="checkbox" name="write_enabled"
                data-bs-toggle="tooltip" title="Un-check for Read-Only token, or leave checked for Write-Capable!"
                {% if token.write_enabled %}checked{% endif %} /></td>
          </tr>
{% endif %}
          <tr>
            <td>Expires</td>
            <td><input
                id="party"
                type="datetime-local"
                name="expires"
                data-bs-toggle="tooltip" title="Select token expiration, or leave blank for none."
                value="{{ token.expires|date:"Y-m-d\TH:i:s" }}" />{# date:"<format>" outputs ISO format for datetime-local element #}
                  {% if settings.API_MAX_TOKEN_DURATION %}<strong>&nbsp;Token cannot expire more the {{ settings.API_MAX_TOKEN_DURATION }} days into the future!<strong>{% endif %}
            </td>
          </tr>
          <tr>
            <td>Allowed IPs</td>
            <td><input type="text" size=80 name="allowed_ips" value="{{ token.allowed_ips }}"
                data-bs-toggle="tooltip" title="Comma-separated list of allowed IPv4/IPv6 networks in CIDR notation. Leave blank to allow all! E.g. 192.168.1.0/24,2001:db8:1::/64" /></td>
          </tr>
          <tr>
            {% if action == "add" %}
              <td>
                <input type="submit"
                value="Add Token"
                class="btn btn-primary"
                data-bs-toggle="tooltip" title="Click here to add a token!"
                {% if request.user.profile.are_you_sure %}
                onclick="return confirm_change('Are you sure you want add a new token ? If so, make sure you have copied down the token string!')"
                {% endif %}
                >
              </td>
              <td>
                {% if not settings.ALLOW_TOKEN_RETRIEVAL %}
                <strong>Make sure you save this new token!!! This is the only time you will see the full token string!</strong>
                {% endif %}
              </td>
            {% else %}{# edit #}
            <td>
                <input type="submit"
                value="Update Token"
                class="btn btn-primary"
                data-bs-toggle="tooltip" title="Click here to update this token!"
                {% if request.user.profile.are_you_sure %}
                onclick="return confirm_change('Are you sure you want update this token ?')"
                {% endif %}
                >
              </td>
              <td></td>
            {% endif %}
          </tr>
        </form>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

openl2m/templates/users/token_list.html
{% extends '_base.html' %}
{% load helpers %}

{% block title %}API Token{% endblock %}

{% block content %}
<div class="row">
  <div class="col">
    <div class="card border-default">
      <div class="card-header bg-default">
      {% if request.user.id == user.id %}
        <strong>Your API Tokens</strong>
      {% else %}
        <strong>API Tokens for '{{ user.username }}'</strong>
      {% endif %}
      </div>
      <div class="card-body">
        <table class="table table-hover table-headings">
          <tbody>
          <tr>
            <th></th>
            <th></th>
            <th>Token</th>
            <th>Expires</th>
            <th>Last Used</th>
            <th>Writable</th>
            <th>Description</th>
          </tr>
          {% if tokens %}
            {% for token in tokens %}
          <tr>
            <td><a href="{% url 'users:token_delete' token.id %}"
                title="Delete token"
                {% if request.user.profile.are_you_sure %}
                onclick="return confirm_change('Are you sure you want to delete this API token ?')"
                {% endif %}
                ><i class="fa-solid fa-trash-alt"></i></a></td>
            <td><a href="{% url 'users:token_edit' token.id %}" title="Edit token"><i class="fa-solid fa-pen"></i></a></td>
            {% if settings.ALLOW_TOKEN_RETRIEVAL %}
            <td>{{token.key }}</td>
            {% else %}
            <td>{{token.partial }}</td>
            {% endif %}
            <td>{{ token.expires }}</td>
            <td>{{ token.last_used }}</td>
            <td>{% if token.write_enabled %}<i class="fa-solid fa-check"></i>{% else %}<i class="fa-solid fa-times"></i>{% endif %}</td>
            <td>{{ token.description }}</td>
          </tr>
            {% endfor %}
          {% endif %}
        </tbody>
        </table>
        {% if not tokens or tokens|length < settings.MAX_API_TOKENS %}
        <a href="{% url 'users:token_add' %}" title="Create a new token"><i class="fa-solid fa-plus-circle"></i> Add a token</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}